config/routes.rb
Rails.application.routes.draw do
  root to: "table#index"
  resources :table, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/table_controller.rb
class TableController < ApplicationController

  # Creates matrices of elements for each column
  def index
    file = File.read("db/data.json")
    @elements = JSON.parse(file)
    @periodicTable = Array.new(10) {Array.new(18)}
    @collumsLegend = Array.new
    @collumsLegend = [nil, 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R']
    @elements["order"].each do |element|
      @periodicTable[@elements[element]["ypos"] - 1][@elements[element]["xpos"] - 1] = element
    end
  end

  def show
    file = File.read("db/data.json")
    elements = JSON.parse(file)
    @element = elements[ params[:id] ]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Tabela Periódica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <%= link_to 'Home', root_url, class: 'navbar-brand' %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PeriodicTable</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/table/index.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track' => true %>
<main>
  <div class="elementData">
    <table id='periodic-table' class="table-sm table-borderless">
      <tbody>
        <tr>
          <% @collumsLegend.each do |collum| %>
            <td><h2><%= collum %></h2></td>
          <% end %>
        </tr>
          <% @periodicTable.each_with_index do |line, i| %>
          <tr>
            <td><h2><%= (i+1) %></h2></td>
            <% line.each_with_index do |element| %>
              <td>
                <% if (element != nil) %>
                <%= link_to table_path(@elements[element]["name"].downcase) do %> 
                  <section class="<%= @elements[element]["category"]%>">
                    <span><%= @elements[element]["number"] %></span>
                    <h2><%= @elements[element]["symbol"] %></h2>
                    <h3><%= @elements[element]["name"] %></h3>
                    <h4><%= @elements[element]["atomic_mass"] %></h4>
                  </section>
                <% end %>
                <%end%>
              </td>
            <% end %>
          </tr>   
          <% end %>
      </tbody>
    </table>
  </div>
  <div class="subtitle">
    <table id='subtitle-table' class="table table-bordered">
      <tbody>
        <tr>
          <td class= "subtitle-header"><h2>Legenda</h2></td>
        </tr><tr>
          <td class= "subtitle-alkali-metal"><h5>Metais Alcalinos</h5></td>
        </tr><tr>
          <td class= "subtitle-alkaline-earth-metal"><h5>Metais Alcalino Terrosos</h5></td>
        </tr><tr>
          <td class= "subtitle-lanthanide"><h5>Lantanídeos</h5></td>
        </tr><tr>
          <td class= "subtitle-actinide"><h5>Actinídios</h5></td>
        </tr><tr>
          <td class= "subtitle-transition-metal"><h5>Metais de Transição</h5></td>
        </tr><tr>
          <td class= "subtitle-post-transition-metal"><h5>Outros Metais</h5></td>
        </tr><tr>
          <td class= "subtitle-metalloid"><h5>Semimetais</h5></td>
        </tr><tr>
          <td class= "subtitle-diatomic-nonmetal"><h5>Não Metais</h5></td>
        </tr><tr>
          <td class= "subtitle-noble-gas"><h5>Gases Nobres</h5></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
</main>

app/views/table/show.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'show', media: 'all', 'data-turbolinks-track' => true %>
<main>
    <div class="elementName">
        <h2><%= @element["name"] %></h1>
    </div>
    <div class="elementBody">
        <div class="elementDiagram">
            <section class="<%= @element["category"]%>">
                <span><%= @element["number"] %></span>
                <h2><%= @element["symbol"] %></h2>
                <h3><%= @element["name"] %></h3>
                <h3><%= @element["shells"] %></h3>
                <h3><%= @element["atomic_mass"] %></h3>
            </section>
        </div>
    </div>
    <div class="dataBody">
        <div class="elementData">
            <table id='element-table' class="table table-bordered">
            <thead  class="thead-dark">
                <tr>
                <th><h5>Dado<h5></th>
                <th><h5>Informação sobre<h5></th>
                </tr>
            </thead>

            <tbody>
                <% @element.each do |key, value| %>
                <tr>
                    <td><h5><%= key %><h5></td>
                    <td><h5><%= value %><h5></td>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>
</main>